import pytest
from django.contrib.auth import get_user_model
from datetime import date
from api.models import GameCategory, Game, Challenge

# This test file was generated by AI. None of these actually touch the real DB.

User = get_user_model()

@pytest.fixture
def user(db):
    return User.objects.create_user(username="alice", password="pw")

@pytest.fixture
def category(db):
    return GameCategory.objects.create(categoryName="Word Games")

@pytest.fixture
def game(db, category):
    return Game.objects.create(name="Anagram Rush", category=category, isMultiplayer=False)

@pytest.fixture
def challenge(db):
    # Minimal challenge just to satisfy FK (not used in skill math)
    from api.models import Group
    g = Group.objects.create(name="Solo")
    return Challenge.objects.create(groupID=g, isPublic=False, startDate=date(2025,1,1), endDate=date(2025,12,31), name="Solo Challenge")
