# This test file was generated by AI.

import math
from datetime import date, timedelta
from freezegun import freeze_time
import pytest
from django.utils import timezone

from api.models import SkillLevel, GamePerformance
from api.services.skill import recompute_skill_for_category
from api.services.skill_config import SKILL_CONFIG
from .utils import current_skill


@pytest.mark.django_db
def test_never_played_returns_zero(user, category):
    # No GamePerformance rows exist
    skill = recompute_skill_for_category(user, category)
    sl = SkillLevel.objects.get(user=user, category=category)
    assert skill == 0.0
    assert sl.totalEarned == 0.0
    assert sl.totalPossible == 0.0


@pytest.mark.django_db
def test_plain_averaging_no_decay_no_window(user, category, game, challenge, monkeypatch):
    # Disable decay & window
    monkeypatch.setattr(SKILL_CONFIG, "HALF_LIFE_DAYS", None)
    monkeypatch.setattr(SKILL_CONFIG, "WINDOW_DAYS", None)

    today = date(2025, 9, 8)
    GamePerformance.objects.create(challenge=challenge, game=game, user=user, date=today, score=80)
    GamePerformance.objects.create(challenge=challenge, game=game, user=user, date=today, score=60)

    skill = recompute_skill_for_category(user, category)
    sl = SkillLevel.objects.get(user=user, category=category)

    # Earned = 140, Possible = 200 → ratio 0.7 → skill 7.0
    assert math.isclose(sl.totalEarned, 140.0, rel_tol=1e-6)
    assert math.isclose(sl.totalPossible, 200.0, rel_tol=1e-6)
    assert math.isclose(skill, 7.0, rel_tol=1e-6)


@pytest.mark.django_db
def test_half_life_decay(user, category, game, challenge, monkeypatch):
    # Enable half-life 30 days, no window
    monkeypatch.setattr(SKILL_CONFIG, "HALF_LIFE_DAYS", 30.0)
    monkeypatch.setattr(SKILL_CONFIG, "WINDOW_DAYS", None)

    base_day = date(2025, 9, 8)
    with freeze_time(base_day):
        # today → weight 1.0
        GamePerformance.objects.create(challenge=challenge, game=game, user=user, date=base_day, score=90)
        # 30 days ago → weight ~0.5
        old_day = base_day - timedelta(days=30)
        GamePerformance.objects.create(challenge=challenge, game=game, user=user, date=old_day, score=60)

        skill = recompute_skill_for_category(user, category)
        sl = SkillLevel.objects.get(user=user, category=category)

        # Earned = 90*1 + 60*0.5 = 120
        # Possible = 100*1 + 100*0.5 = 150
        # Ratio = 120/150 = 0.8 → skill = 8.0
        assert math.isclose(sl.totalEarned, 120.0, rel_tol=1e-6)
        assert math.isclose(sl.totalPossible, 150.0, rel_tol=1e-6)
        assert math.isclose(skill, 8.0, rel_tol=1e-6)


@pytest.mark.django_db
def test_window_cutoff(user, category, game, challenge, monkeypatch):
    # Window 10 days, no decay
    monkeypatch.setattr(SKILL_CONFIG, "WINDOW_DAYS", 10)
    monkeypatch.setattr(SKILL_CONFIG, "HALF_LIFE_DAYS", None)

    today = date(2025, 9, 8)
    recent = today - timedelta(days=5)
    old = today - timedelta(days=20)

    # Only the recent one should count
    GamePerformance.objects.create(challenge=challenge, game=game, user=user, date=recent, score=50)
    GamePerformance.objects.create(challenge=challenge, game=game, user=user, date=old, score=100)

    # Freeze "now" to today so window is deterministic
    with freeze_time(today):
        skill = recompute_skill_for_category(user, category)
        sl = SkillLevel.objects.get(user=user, category=category)

    assert math.isclose(sl.totalEarned, 50.0, rel_tol=1e-6)
    assert math.isclose(sl.totalPossible, 100.0, rel_tol=1e-6)
    assert math.isclose(skill, 5.0, rel_tol=1e-6)


@pytest.mark.django_db
def test_signals_recompute_on_save_and_delete(user, category, game, challenge, monkeypatch):
    # Disable decay/window
    monkeypatch.setattr(SKILL_CONFIG, "HALF_LIFE_DAYS", None)
    monkeypatch.setattr(SKILL_CONFIG, "WINDOW_DAYS", None)

    today = date(2025, 9, 8)

    # Create → should recompute via post_save signal
    gp = GamePerformance.objects.create(challenge=challenge, game=game, user=user, date=today, score=70)
    sl = SkillLevel.objects.get(user=user, category=category)
    assert math.isclose(current_skill(sl), 7.0, rel_tol=1e-6)

    # Update score → another save → recompute
    gp.score = 90
    gp.save()
    sl.refresh_from_db()
    assert math.isclose(current_skill(sl), 9.0, rel_tol=1e-6)

    # Delete → post_delete signal → skill back to 0
    gp.delete()
    sl.refresh_from_db()
    assert sl.totalEarned == 0.0
    assert sl.totalPossible == 0.0
    assert current_skill(sl) == 0.0
