import pytest
from django.utils import timezone
from datetime import timedelta

from api.models import (
    Obligation, Payment,
    PaymentMethod, PaymentStatus,
    ObligationStatus,
)
from api.tasks import auto_confirm_old_payments

# This file was generated by AI.

def test_auto_confirm_task(db, users, challenge):
    alice, bob, _ = users
    challenge.winner = alice
    challenge.save()

    # Bob owes Alice
    ob = Obligation.objects.create(
        challenge=challenge, payer=bob, payee=alice,
        amount=5, due_at=timezone.now() + timedelta(days=7),
        status=ObligationStatus.PENDING,
    )

    # Create a PENDING payment older than 2 days
    past_time = timezone.now() - timedelta(days=2, hours=1)
    pay = Payment.objects.create(
        obligation=ob,
        method=PaymentMethod.CASH,
        amount=5,
        status=PaymentStatus.PENDING,
    )

    # override the auto_now_add value so it's >48 h old
    pay.payer_marked_at = past_time
    pay.save(update_fields=["payer_marked_at"])

    # Run the task (force threshold = 1 hour so our 49-hour payment is caught)
    auto_confirm_old_payments.run(1)

    pay.refresh_from_db()
    ob.refresh_from_db()
    assert pay.status == PaymentStatus.CONFIRMED
    assert ob.status == ObligationStatus.PAID
