import pytest
from datetime import timedelta
from django.urls import reverse
from django.utils import timezone

from api.models import (
    Obligation, Payment, PaymentMethod, PaymentProvider,
    PaymentStatus, ObligationStatus,
)
# This file was generated by AI.

def test_finalize_creates_obligations(client, users, challenge):
    alice, bob, _ = users
    challenge.winner = alice
    challenge.save()

    client.force_login(alice)
    url = reverse('finalize-challenge', args=[challenge.id])
    resp = client.post(url)
    assert resp.status_code == 201
    assert Obligation.objects.filter(challenge=challenge).count() == 2


def test_payer_marks_external_payment(client, users, challenge):
    alice, bob, _ = users
    challenge.winner = alice
    challenge.save()
    ob = Obligation.objects.create(
        challenge=challenge, payer=bob, payee=alice,
        amount=5, due_at=timezone.now() + timedelta(days=7)
    )

    client.force_login(bob)
    url = reverse('obligation-pay-external', args=[ob.id])
    resp = client.post(url, {
        "provider": PaymentProvider.VENMO,
        "amount": "5.00",
        "note": "gg",
    })
    assert resp.status_code == 201
    assert Payment.objects.filter(obligation=ob).exists()


def test_winner_confirms_payment(client, users, challenge):
    alice, bob, _ = users
    challenge.winner = alice
    challenge.save()
    ob = Obligation.objects.create(
        challenge=challenge, payer=bob, payee=alice,
        amount=5, due_at=timezone.now() + timedelta(days=7)
    )
    pay = Payment.objects.create(
        obligation=ob, method=PaymentMethod.CASH, amount=5
    )

    client.force_login(alice)
    url = reverse('payment-confirm', args=[pay.id])
    resp = client.post(url)
    pay.refresh_from_db(); ob.refresh_from_db()
    assert resp.status_code == 200
    assert pay.status == PaymentStatus.CONFIRMED
    assert ob.status  == ObligationStatus.PAID
