stages:
  - test

variables:
  # Prevents Django from using your production DB
  DATABASE_URL: "sqlite:///db.sqlite3"
  PYTHONPATH: "${CI_PROJECT_DIR}"
  DJANGO_SETTINGS_MODULE: "myserver.settings"

# Cache dependencies to speed up CI
cache:
  paths:
    - .venv/
    - node_modules/

test_backend:
  stage: test
  image: python:3.11
  before_script:
    - python -m venv .venv
    - .venv\Scripts\Activate.ps1
    - python -m pip install --upgrade pip
    - python -m pip install -r requirements.txt
  script:
    - python manage.py test api.tests --noinput
  artifacts:
    when: always

test_frontend:
  stage: test
  image: node:20
  before_script:
    - npm ci
  script:
    - cd src
    - npm run test:unit:ci
  artifacts:
    paths:
      - src/coverage/
    when: always
