# Generated by Django 5.1.7 on 2025-11-11 02:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('imageUrl', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'Badges',
            },
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'GameCategories',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Group', max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(default='Anonymous', max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('numCoins', models.IntegerField(default=0)),
                ('memojiBgColor', models.CharField(default='#ffffff', max_length=7)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission')),
            ],
            options={
                'db_table': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AlarmSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.IntegerField()),
                ('alarmTime', models.TimeField()),
                ('uID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AlarmSchedules',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPublic', models.BooleanField(default=False)),
                ('isPending', models.BooleanField(default=False)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('totalDays', models.IntegerField(null=True)),
                ('name', models.CharField(default='Challenge', max_length=255)),
                ('isCompleted', models.BooleanField(default=False)),
                ('daysCompleted', models.IntegerField(default=0)),
                ('participationFee', models.IntegerField(default=0)),
                ('unlockedCoins', models.IntegerField(db_default=0, default=0)),
                ('rewards_finalized', models.BooleanField(default=False)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Challenges',
            },
        ),
        migrations.CreateModel(
            name='ChallengeBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betAmount', models.IntegerField()),
                ('isPending', models.BooleanField()),
                ('isCompleted', models.BooleanField(default=False)),
                ('isCollected', models.BooleanField(default=False)),
                ('initiatorRefunded', models.BooleanField(default=False)),
                ('recipientRefunded', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets_initiated', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets_received', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bets_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ChallengeBets',
            },
        ),
        migrations.CreateModel(
            name='ChallengeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasSetAlarms', models.BooleanField(default=False, null=True)),
                ('challengeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
                ('uID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ChallengeMemberships',
                'unique_together': {('challengeID', 'uID')},
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='members',
            field=models.ManyToManyField(related_name='challenges', through='api.ChallengeMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isMultiplayer', models.BooleanField(null=True)),
                ('route', models.CharField(blank=True, max_length=64, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gamecategory')),
            ],
            options={
                'db_table': 'Games',
            },
        ),
        migrations.CreateModel(
            name='GameSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.IntegerField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
            ],
            options={
                'db_table': 'GameSchedules',
                'unique_together': {('challenge', 'dayOfWeek')},
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='groupID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.group'),
        ),
        migrations.CreateModel(
            name='GroupChallengeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.IntegerField()),
                ('chall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('uID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupChallengeInvites',
            },
        ),
        migrations.CreateModel(
            name='GroupInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_group_invites', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Memoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.URLField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.memoji')),
            ],
            options={
                'db_table': 'Memojies',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='currentMemoji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_using_this_memoji', to='api.memoji'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=True)),
                ('groupID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='api.group')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'PendingConfirm'), ('paid', 'Paid')], default='unpaid', max_length=16)),
                ('due_at', models.DateTimeField()),
                ('points_penalty_per_day', models.IntegerField(default=0)),
                ('last_penalty_at', models.DateTimeField(blank=True, null=True)),
                ('agreement_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='api.challenge')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_obligations_to_receive', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_obligations_to_pay', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('challenge', 'payer', 'payee')},
            },
        ),
        migrations.CreateModel(
            name='PatternMemorizationGameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_rounds', models.IntegerField(default=5)),
                ('current_round', models.IntegerField(default=1)),
                ('pattern_sequence', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('join_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('joins_closed', models.BooleanField(blank=True, default=False, null=True)),
                ('alarmDateTime', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_games', to='api.challenge')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PatternMemorizationGameStates',
                'unique_together': {('challenge', 'game', 'alarmDateTime', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('external', 'External'), ('custom', 'Custom')], max_length=16)),
                ('provider', models.CharField(blank=True, choices=[('venmo', 'Venmo'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('payer_marked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'PendingConfirm'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('winner_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_photo', models.ImageField(blank=True, null=True, upload_to='reward_evidence/')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.obligation')),
            ],
        ),
        migrations.CreateModel(
            name='PendingGroupChallengeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.IntegerField()),
                ('alarmTime', models.TimeField()),
                ('chall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
                ('uID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PendingGroupChallengeAvailabilities',
            },
        ),
        migrations.CreateModel(
            name='PublicChallengeCategoryAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.gamecategory')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
            ],
            options={
                'db_table': 'PublicChallengeCategoryAssociations',
            },
        ),
        migrations.CreateModel(
            name='PublicChallengeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('averageSkillLevel', models.DecimalField(decimal_places=2, max_digits=4)),
                ('isMultiplayer', models.BooleanField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
            ],
            options={
                'db_table': 'PublicChallengeConfigurations',
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expo_push_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RewardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('money', 'Money'), ('points', 'Points'), ('custom', 'Custom')], default='money', max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_setting', to='api.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='SudokuGameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle', models.JSONField()),
                ('solution', models.JSONField()),
                ('game_code', models.CharField(default='sudoku', editable=False, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('join_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('joins_closed', models.BooleanField(blank=True, default=False, null=True)),
                ('alarmDateTime', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='api.challenge')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SudokuGameStates',
                'unique_together': {('challenge', 'game', 'alarmDateTime', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TypingRaceGameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('game_code', models.CharField(default='typing_race', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('join_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('joins_closed', models.BooleanField(blank=True, default=False, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_race_games', to='api.challenge')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
            options={
                'db_table': 'TypingRaceGameStates',
            },
        ),
        migrations.CreateModel(
            name='UserAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.IntegerField()),
                ('alarmTime', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserAvailabilities',
            },
        ),
        migrations.CreateModel(
            name='UserMemoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by_users', to='api.memoji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_memojies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserMemojies',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=255)),
                ('body', models.TextField(default='')),
                ('type', models.CharField(default='generic', max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('screen', models.CharField(blank=True, default='Messages', max_length=64)),
                ('challengeId', models.IntegerField(blank=True, null=True)),
                ('challName', models.CharField(blank=True, max_length=255, null=True)),
                ('whichChall', models.CharField(blank=True, max_length=64, null=True)),
                ('groupId', models.IntegerField(blank=True, null=True)),
                ('startDate', models.CharField(blank=True, max_length=64, null=True)),
                ('endDate', models.CharField(blank=True, max_length=64, null=True)),
                ('accepted', models.IntegerField(blank=True, null=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordleGameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle', models.JSONField()),
                ('solution', models.JSONField()),
                ('game_code', models.CharField(default='wordle', max_length=50)),
                ('answer', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('join_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('joins_closed', models.BooleanField(blank=True, default=False, null=True)),
                ('alarmDateTime', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordle_games', to='api.challenge')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WordleGameStates',
                'unique_together': {('challenge', 'game', 'alarmDateTime', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeAlarmSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alarmschedule')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
            ],
            options={
                'db_table': 'ChallengeAlarmSchedules',
                'unique_together': {('challenge', 'alarm_schedule')},
            },
        ),
        migrations.CreateModel(
            name='ExternalHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('venmo', 'Venmo'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=16)),
                ('handle', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_handles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FriendRequests',
                'unique_together': {('sender', 'recipient')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uID1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to=settings.AUTH_USER_MODEL)),
                ('uID2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Friendships',
                'unique_together': {('uID1', 'uID2')},
            },
        ),
        migrations.CreateModel(
            name='GamePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.IntegerField()),
                ('auto_generated', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GamePerformances',
                'unique_together': {('challenge', 'game', 'user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GameScheduleGameAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_order', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('game_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gameschedule')),
            ],
            options={
                'db_table': 'GameScheduleGameAssociations',
                'unique_together': {('game_schedule', 'game_order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='challenge',
            unique_together={('groupID', 'name')},
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('uID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupMemberships',
                'unique_together': {('groupID', 'uID')},
            },
        ),
        migrations.CreateModel(
            name='PatternMemorizationGamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds_completed', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('last_round_success', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patternmemorizationgamestate')),
            ],
            options={
                'db_table': 'PatternMemorizationPlayers',
                'unique_together': {('game_state', 'player')},
            },
        ),
        migrations.CreateModel(
            name='PersonalChallengeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('chall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_invite', to='api.challenge')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_personal_chall_invites', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_personal_chall_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PersonalChallengeInvites',
                'unique_together': {('chall', 'recipient')},
            },
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalEarned', models.IntegerField(null=True)),
                ('totalPossible', models.IntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gamecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SkillLevels',
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='SudokuGamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracyCount', models.IntegerField()),
                ('inaccuracyCount', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gameState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sudokugamestate')),
            ],
            options={
                'db_table': 'SudokuGamePlayers',
                'unique_together': {('gameState', 'player')},
            },
        ),
        migrations.CreateModel(
            name='TypingRaceGamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=100.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.typingracegamestate')),
            ],
            options={
                'db_table': 'TypingRaceGamePlayers',
                'unique_together': {('game_state', 'player')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected', models.BooleanField(default=False)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by_users', to='api.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserBadges',
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='WordleGamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracyCount', models.IntegerField()),
                ('inaccuracyCount', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gameState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wordlegamestate')),
            ],
            options={
                'db_table': 'WordleGamePlayers',
                'unique_together': {('gameState', 'player')},
            },
        ),
        migrations.CreateModel(
            name='WordleMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('guess', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gameState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='api.wordlegamestate')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordle_moves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('gameState', 'player', 'row')},
            },
        ),
    ]
