# Generated by Django 5.2 on 2025-04-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecategory',
            name='categoryName',
            field=models.CharField(max_length=255),
        ),
    ]
