# Generated by Django 5.1.7 on 2025-04-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudokugameplayer',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
