# Generated by Django 5.1.7 on 2025-10-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='screen',
            field=models.CharField(
                max_length=64,
                default='Messages',
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='challengeId',
            field=models.IntegerField(
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='challName',
            field=models.CharField(
                max_length=255,
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='whichChall',
            field=models.CharField(
                max_length=64,
                null=True,
                blank=True
            ),
        ),
    ]