# Generated by Django 5.1.7 on 2025-08-29 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternMemorizationGameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_rounds', models.IntegerField(default=5)),
                ('current_round', models.IntegerField(default=1)),
                ('pattern_sequence', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_games', to='api.challenge')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
            options={
                'db_table': 'PatternMemorizationGameStates',
            },
        ),
        migrations.CreateModel(
            name='PatternMemorizationGamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds_completed', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('last_round_success', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patternmemorizationgamestate')),
            ],
            options={
                'db_table': 'PatternMemorizationPlayers',
                'unique_together': {('game_state', 'player')},
            },
        ),
    ]
