# Generated by Django 5.1.7 on 2025-10-28 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingRaceGameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('game_code', models.CharField(default='typing_race', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('join_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('joins_closed', models.BooleanField(blank=True, default=False, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_race_games', to='api.challenge')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
            options={
                'db_table': 'TypingRaceGameStates',
            },
        ),
        migrations.CreateModel(
            name='TypingRaceGamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=100.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.typingracegamestate')),
            ],
            options={
                'db_table': 'TypingRaceGamePlayers',
                'unique_together': {('game_state', 'player')},
            },
        ),
    ]
