# Generated by Django 5.1.7 on 2025-08-27 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingGroupChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endDate', models.DateField()),
                ('name', models.CharField(default='Challenge', max_length=255)),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
            options={
                'db_table': 'PendingGroupChallenges',
            },
        ),
        migrations.CreateModel(
            name='GroupChallengeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pendingChall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pendinggroupchallenge')),
            ],
            options={
                'db_table': 'GroupChallengeInvites',
            },
        ),
        migrations.CreateModel(
            name='PendingGroupChallengeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.IntegerField()),
                ('alarmTime', models.TimeField()),
                ('pendingChall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pendinggroupchallenge')),
                ('uID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PendingGroupChallengeAvailabilities',
            },
        ),
    ]
