# Generated by Django 5.1.7 on 2025-08-29 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameperformance',
            unique_together={('challenge', 'game', 'user', 'date')},
        ),
    ]
