# Generated by Django 5.1.7 on 2025-10-25 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='participationFee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='numCoins',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ChallengeBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betAmount', models.IntegerField()),
                ('isPending', models.BooleanField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets_initiated', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ChallengeBets',
            },
        ),
    ]
