# Generated by Django 5.2 on 2025-04-09 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gamecategory_group_alter_user_managers_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='isMultiplayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='challenge',
            unique_together={('groupID', 'name')},
        ),
        migrations.CreateModel(
            name='SudokuGamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracyCount', models.IntegerField()),
                ('inaccuracyCount', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SudokuGamePlayers',
            },
        ),
        migrations.CreateModel(
            name='SudokuGameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle', models.JSONField()),
                ('solution', models.JSONField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='api.challenge')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('players', models.ManyToManyField(related_name='sudoku_games', through='api.SudokuGamePlayer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SudokuGameStates',
            },
        ),
        migrations.AddField(
            model_name='sudokugameplayer',
            name='gameState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sudokugamestate'),
        ),
        migrations.CreateModel(
            name='ChallengeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
                ('uID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ChallengeMemberships',
                'unique_together': {('challengeID', 'uID')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='sudokugameplayer',
            unique_together={('gameState', 'player')},
        ),
    ]
