# Generated by Django 5.1.7 on 2025-11-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_typingracegamestate_alarmdatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numCoins',
            field=models.IntegerField(default=20),
        ),
    ]
