# Generated by Django 5.1.7 on 2025-10-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20251007_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='totalDays',
            field=models.IntegerField(
                null=True
            ),
        ),
    ]
