# Generated by Django 5.1.7 on 2025-09-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patternmemorizationgamestate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternmemorizationgameplayer',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
