# Generated by Django 5.1.7 on 2025-08-29 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pendinggroupchallenge_groupchallengeinvite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchallengeinvite',
            name='groupID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.group'),
            preserve_default=False,
        ),
    ]
