# Generated by Django 5.2 on 2025-04-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gamecategory_ismultiplayer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='uID',
        ),
        migrations.RemoveField(
            model_name='sudokugamestate',
            name='players',
        ),
        migrations.AddField(
            model_name='challenge',
            name='daysCompleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='gamecategory',
            unique_together={('categoryName', 'isMultiplayer')},
        ),
    ]
