# Generated by Django 5.1.7 on 2025-08-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_groupchallengeinvite_groupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchallengeinvite',
            name='accepted',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
