# Generated by Django 5.1.7 on 2025-10-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userbadge_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbadge',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
