# Generated by Django 5.1.7 on 2025-09-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_groupchallengeinvite_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='isPublic',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
