# Generated by Django 5.2 on 2025-04-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_challenge_uid_remove_sudokugamestate_players_and_more'),
        ('api', '0004_remove_challenge_uid_remove_sudokugamestate_players_and_more'),
    ]

    operations = [
    ]
