# Generated by Django 5.1.7 on 2025-09-04 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_gameperformance_unique_together'),
        ('api', '0005_challenge_ispublic'),
    ]

    operations = [
    ]
