# Generated by Django 5.1.7 on 2025-10-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userbadge_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengebet',
            name='isCollected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challengebet',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
