# Generated by Django 5.1.7 on 2025-10-31 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_challengebet_iscollected_challengebet_iscompleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.URLField(max_length=500)),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.memoji')),
            ],
            options={
                'db_table': 'Memojies',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='current_memoji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_using_this_memoji', to='api.memoji'),
        ),
        migrations.CreateModel(
            name='UserMemoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by_users', to='api.memoji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_memojies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserMemojies',
            },
        ),
    ]
