# Generated by Django 5.1.7 on 2025-09-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20250903_1839'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamecategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='game',
            name='isMultiplayer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamecategory',
            name='categoryName',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='gamecategory',
            name='isMultiplayer',
        ),
    ]
