# Generated by Django 5.1.7 on 2025-09-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_gamecategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllevel',
            name='totalEarned',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='totalPossible',
            field=models.FloatField(default=0.0),
        ),
    ]
