# Generated by Django 5.1.7 on 2025-10-31 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_memoji_user_current_memoji_usermemoji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_memoji',
            new_name='currentMemoji',
        ),
    ]
