# Generated by Django 5.1.7 on 2025-09-07 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_gamecategory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchallengeinvite',
            name='pendingChall',
        ),
        migrations.RemoveField(
            model_name='pendinggroupchallengeavailability',
            name='pendingChall',
        ),
        migrations.AddField(
            model_name='challenge',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='isPending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupchallengeinvite',
            name='chall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.challenge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendinggroupchallengeavailability',
            name='chall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.challenge'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='PendingGroupChallenge',
        ),
    ]
