# Generated by Django 5.1.7 on 2025-11-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_current_memoji_user_currentmemoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoji',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='memojiBgColor',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
