# Generated by Django 5.1.7 on 2025-09-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_skilllevel_totalearned_and_more'),
        ('api', '0008_remove_groupchallengeinvite_pendingchall_and_more'),
    ]

    operations = [
    ]
