# Generated by Django 5.1.7 on 2025-11-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fcmdevice_groupinvite'),
        ('api', '0002_typingracegamestate_typingracegameplayer'),
        ('api', '0009_memoji_price_user_memojibgcolor'),
    ]

    operations = [
    ]
