# Generated by Django 5.1.7 on 2025-09-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20250908_0014'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gameperformance',
            index=models.Index(fields=['user'], name='GamePerform_user_id_601aee_idx'),
        ),
        migrations.AddIndex(
            model_name='gameperformance',
            index=models.Index(fields=['game'], name='GamePerform_game_id_20837f_idx'),
        ),
        migrations.AddIndex(
            model_name='gameperformance',
            index=models.Index(fields=['date'], name='GamePerform_date_f9900e_idx'),
        ),
        migrations.AddIndex(
            model_name='gameperformance',
            index=models.Index(fields=['user', 'date'], name='GamePerform_user_id_dff05f_idx'),
        ),
        migrations.AddIndex(
            model_name='gameperformance',
            index=models.Index(fields=['game', 'date'], name='GamePerform_game_id_0bc65e_idx'),
        ),
    ]
