# Generated by Django 5.1.7 on 2025-11-05 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20251104_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengebet',
            name='initiatorRefunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challengebet',
            name='recipientRefunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='accepted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='endDate',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='groupId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='startDate',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
