# Generated by Django 5.1.7 on 2025-09-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_gameperformance_gameperform_user_id_601aee_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudokugamestate',
            name='game_code',
            field=models.CharField(default='sudoku', editable=False, max_length=16),
        ),
    ]
