# Generated by Django 5.1.7 on 2025-11-07 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_message_is_read_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sudokugamestate',
            unique_together={('challenge', 'game', 'alarmDateTime', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='wordlegamestate',
            unique_together={('challenge', 'game', 'alarmDateTime', 'user')},
        ),
    ]
