# Generated by Django 5.1.7 on 2025-09-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20250908_1550'),
        ('api', '0011_sudokugamestate_game_code'),
    ]

    operations = [
    ]
