# Generated by Django 5.1.7 on 2025-09-10 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sudokugamestate_game_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'PendingConfirm'), ('paid', 'Paid')], default='unpaid', max_length=16)),
                ('due_at', models.DateTimeField()),
                ('points_penalty_per_day', models.IntegerField(default=0)),
                ('last_penalty_at', models.DateTimeField(blank=True, null=True)),
                ('agreement_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='api.challenge')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_obligations_to_receive', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_obligations_to_pay', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('challenge', 'payer', 'payee')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('external', 'External')], max_length=16)),
                ('provider', models.CharField(blank=True, choices=[('venmo', 'Venmo'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('payer_marked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'PendingConfirm'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('winner_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_photo', models.ImageField(blank=True, null=True, upload_to='reward_evidence/')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.obligation')),
            ],
        ),
        migrations.CreateModel(
            name='RewardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('money', 'Money'), ('points', 'Points'), ('custom', 'Custom')], default='money', max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_setting', to='api.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('venmo', 'Venmo'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=16)),
                ('handle', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_handles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
