# Generated by Django 5.1.7 on 2025-11-05 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_challengebet_initiatorrefunded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengebet',
            name='initiatorRefunded',
        ),
        migrations.RemoveField(
            model_name='challengebet',
            name='recipientRefunded',
        ),
    ]
