# Generated by Django 5.1.7 on 2025-11-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_challengebet_initiatorrefunded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='unlockedCoins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengebet',
            name='initiatorRefunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challengebet',
            name='recipientRefunded',
            field=models.BooleanField(default=False),
        ),
    ]
