# Generated by Django 5.1.7 on 2025-09-10 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_obligation_payment_rewardsetting_externalhandle'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='members',
            field=models.ManyToManyField(related_name='challenges', through='api.ChallengeMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='rewards_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
