# Generated by Django 5.1.7 on 2025-11-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_challenge_unlockedcoins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='unlockedCoins',
            field=models.IntegerField(db_default=0, default=0),
        ),
    ]
