# Generated by Django 5.1.7 on 2025-09-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20250910_0840'),
        ('api', '0013_challenge_members_challenge_rewards_finalized_and_more'),
    ]

    operations = [
    ]
