# Generated by Django 5.1.7 on 2025-09-12 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20250911_1817'),
        ('api', '0014_merge_20250911_2144'),
    ]

    operations = [
    ]
