# Generated by Django 5.1.7 on 2025-09-16 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20250911_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordleGameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle', models.JSONField()),
                ('solution', models.JSONField()),
                ('game_code', models.CharField(default='wordle', max_length=50)),
                ('answer', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordle_games', to='api.challenge')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
            options={
                'db_table': 'WordleGameStates',
            },
        ),
        migrations.CreateModel(
            name='WordleGamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracyCount', models.IntegerField()),
                ('inaccuracyCount', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gameState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wordlegamestate')),
            ],
            options={
                'db_table': 'WordleGamePlayers',
                'unique_together': {('gameState', 'player')},
            },
        ),
        migrations.CreateModel(
            name='WordleMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('guess', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gameState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='api.wordlegamestate')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordle_moves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('gameState', 'player', 'row')},
            },
        ),
    ]
