# Generated by Django 5.1.7 on 2025-09-18 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_wordlegamestate_wordlegameplayer_wordlemove'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicChallengeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('averageSkillLevel', models.DecimalField(decimal_places=2, max_digits=4)),
                ('isMultiplayer', models.BooleanField()),
            ],
            options={
                'db_table': 'PublicChallengeConfigurations',
            },
        ),
        migrations.CreateModel(
            name='UserAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.IntegerField()),
                ('alarmTime', models.TimeField()),
            ],
            options={
                'db_table': 'UserAvailabilities',
            },
        ),
        migrations.RemoveIndex(
            model_name='gameperformance',
            name='GamePerform_user_id_601aee_idx',
        ),
        migrations.RemoveIndex(
            model_name='gameperformance',
            name='GamePerform_game_id_20837f_idx',
        ),
        migrations.RemoveIndex(
            model_name='gameperformance',
            name='GamePerform_date_f9900e_idx',
        ),
        migrations.RemoveIndex(
            model_name='gameperformance',
            name='GamePerform_user_id_dff05f_idx',
        ),
        migrations.RemoveIndex(
            model_name='gameperformance',
            name='GamePerform_game_id_0bc65e_idx',
        ),
        migrations.RemoveField(
            model_name='sudokugamestate',
            name='game_code',
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='totalEarned',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='totalPossible',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='publicchallengeconfiguration',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.gamecategory'),
        ),
        migrations.AddField(
            model_name='publicchallengeconfiguration',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge'),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
