# Generated by Django 5.1.7 on 2025-09-19 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_wordlegamestate_wordlegameplayer_wordlemove'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalChallengeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_invite', to='api.challenge')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_personal_chall_invites', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_personal_chall_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PersonalChallengeInvites',
                'unique_together': {('chall', 'recipient')},
            },
        ),
    ]
