# Generated by Django 5.1.7 on 2025-09-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_publicchallengeconfiguration_useravailability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='totalDays',
            field=models.IntegerField(null=True),
        ),
    ]
