# Generated by Django 5.1.7 on 2025-09-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_challenge_totaldays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='endDate',
            field=models.DateField(null=True),
        ),
    ]
