# Generated by Django 5.1.7 on 2025-09-25 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_personalchallengeinvite'),
        ('api', '0019_alter_challenge_enddate'),
    ]

    operations = [
    ]
