# Generated by Django 5.1.7 on 2025-09-25 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_20250924_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicchallengeconfiguration',
            name='category',
        ),
        migrations.AddField(
            model_name='sudokugamestate',
            name='game_code',
            field=models.CharField(default='sudoku', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('external', 'External'), ('custom', 'Custom')], max_length=16),
        ),
        migrations.CreateModel(
            name='PublicChallengeCategoryAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.gamecategory')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
            ],
            options={
                'db_table': 'PublicChallengeCategoryAssociations',
            },
        ),
    ]
