# Generated by Django 5.1.7 on 2025-09-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_publicchallengeconfiguration_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='route',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
