# Generated by Django 5.1.7 on 2025-10-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_game_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemembership',
            name='hasSetAlarms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='totalEarned',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='totalPossible',
            field=models.IntegerField(null=True),
        ),
    ]
