# Generated by Django 5.1.7 on 2025-10-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_challengemembership_hassetalarms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengemembership',
            name='hasSetAlarms',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='isMultiplayer',
            field=models.BooleanField(null=True),
        ),
    ]
