# Generated by Django 5.1.7 on 2025-10-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_challengemembership_hassetalarms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='endDate',
            field=models.DateField(default='2025-11-07'),
            preserve_default=False,
        ),
    ]
