# Generated by Django 5.1.7 on 2025-10-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_externalhandle_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternmemorizationgamestate',
            name='joins_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sudokugamestate',
            name='joins_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='wordlegamestate',
            name='joins_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
