# Generated by Django 5.1.7 on 2025-10-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_challenge_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='endDate',
            field=models.DateField(null=True),
        ),
    ]
