# Generated by Django 5.1.7 on 2025-10-08 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_challenge_enddate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set(),
        ),
    ]
