# Generated by Django 5.1.7 on 2025-10-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_patternmemorizationgamestate_joins_closed_and_more'),
        ('api', '0027_alter_game_unique_together'),
    ]

    operations = [
    ]
