"use client"

import type React from "react";
import {
  View,
  Text,
  StyleSheet,
  TextInput,
  SectionList,
  TouchableOpacity,
  ActivityIndicator,
  ImageBackground,
  Platform,
} from "react-native";
import DateTimePicker from "@react-native-community/datetimepicker";
import { Ionicons } from "@expo/vector-icons";
import { useRoute, type NavigationProp } from "@react-navigation/native";
import { useState, useEffect, useMemo, useCallback } from "react";
import axios from "axios";
import { endpoints, leaderboardHistory } from "../../api";   // <- helper added in api.ts

type LeaderRow = { name: string; points: number; rank: number };
type RouteParams = { challId: number; myName: string };
type Props = { navigation: NavigationProp<any> };

// To display the dates correctly; generated by AI
const parseLocalDate = (iso: string) => {
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(y, m - 1, d);       // Month is 0-based
};
const toISODate = (d: Date) =>
  new Date(d.getFullYear(), d.getMonth(), d.getDate())
    .toISOString()
    .slice(0, 10);

const LeaderboardDetails: React.FC<Props> = ({ navigation }) => {
  /* ───────────────────────── params ───────────────────────── */
  const { params } = useRoute() as { params: RouteParams };
  const { challId, myName } = params;

  /* ──────────────────────── state ─────────────────────────── */
  const [rows, setRows]       = useState<LeaderRow[]>([]);
  const [history, setHistory] = useState<Record<string, LeaderRow[]>>({});
  const [loading, setLoading] = useState(true);
  const [err, setErr]         = useState<string | null>(null);

  const [query, setQuery]     = useState("");
  const [showHistory, setShowHistory] = useState(false);

  /* date-range picker */
  const [minDate, setMinDate] = useState<Date | null>(null);   // challenge start
  const [maxDate, setMaxDate] = useState<Date | null>(null);   // challenge end
  const [startDate, setStartDate] = useState<string | null>(null);
  const [endDate,   setEndDate]   = useState<string | null>(null);

  /* which picker is open? (null → none) */
  const [picker, setPicker] = useState<"start" | "end" | null>(null);

  useEffect(() => {
    let ignore = false;

    (async () => {
      setLoading(true);
      setErr(null);

      try {
        const res = await axios.get(endpoints.leaderboard(challId), {
          withCredentials: true,
        });
        if (ignore) return;

        const data = res.data;
        console.log(data)
        setRows(Array.isArray(data) ? data : data.leaderboard ?? []);
      } catch {
        if (!ignore) setErr("Failed to load leaderboard");
      } finally {
        if (!ignore) setLoading(false);
      }
    })();

    return () => { ignore = true; };
  }, [challId]);

    // fetch start/end dates from challenge details
    useEffect(() => {
      let cancelled = false;

      (async () => {
        try {
          // GET /api/challenge-detail/<id>/  →  { startDate: "YYYY-MM-DD", endDate: "YYYY-MM-DD", ... }
          const res = await axios.get(endpoints.challengeDetail(challId), {
            withCredentials: true,
          });
          if (cancelled) return;

            setMinDate(parseLocalDate(res.data.startDate));   // 2025-09-02
            setMaxDate(parseLocalDate(res.data.endDate));     // 2025-09-04
        } catch {
          // if this fails, the picker will simply stay disabled
        }
      })();

      return () => {
        cancelled = true;
      };
    }, [challId]);

  useEffect(() => {
    let ignore = false;

    /* if user hasn’t chosen any range we don’t fetch */
    if (!showHistory) return;
    if (!startDate && !endDate) { setHistory({}); return; }

    (async () => {
      setLoading(true);
      setErr(null);
      try {
        const url = leaderboardHistory(challId, startDate ?? undefined, endDate ?? undefined);
        const res = await axios.get(url, { withCredentials: true });
        if (!ignore) setHistory(res.data.history ?? {});
      } catch {
        if (!ignore) setErr("Failed to load history");
      } finally {
        if (!ignore) setLoading(false);
      }
    })();

    return () => { ignore = true; };
  }, [challId, showHistory, startDate, endDate]);

  /* ─────────────────────── helpers ─────────────────────────── */
  const filterRows = (arr: LeaderRow[]) => {
    const q = query.trim().toLowerCase();
    return q ? arr.filter(r => r.name.toLowerCase().includes(q)) : arr;
  };

  const sectionData = useMemo(() => {
    if (!showHistory) return [];
    return Object.entries(history)
      .sort((a, b) => (a[0] < b[0] ? 1 : -1))
      .map(([date, list]) => ({ title: date, data: filterRows(list) }));
  }, [history, showHistory, query]);

  const listData = useMemo(() => filterRows(rows), [rows, query]);

  const renderRow = useCallback(
    ({ item }: { item: LeaderRow }) => (
      <View style={[styles.row, item.name === myName && styles.meRow]}>
        <Text style={styles.rank}>{item.rank}.</Text>
        <Text style={[styles.name, item.name === myName && styles.meName]}>
          {item.name === myName ? "You" : item.name}
        </Text>
        <Text style={styles.points}>{item.points}</Text>
      </View>
    ),
    [myName]
  );

  /* ─────────────────────── ui ──────────────────────────────── */
  return (
    <ImageBackground source={require("../../images/cgpt.png")} style={styles.bg} resizeMode="cover">
      <View style={styles.container}>
        {/* header */}
        <View style={styles.header}>
          <TouchableOpacity onPress={() => navigation.goBack()} style={styles.iconBtn}>
            <Ionicons name="arrow-back" size={24} color="#fff" />
          </TouchableOpacity>
            <Text style={styles.h1}>Leaderboard</Text>
          <View style={{ width: 40 }} />
        </View>

        {/* toggle */}
        <View style={styles.toggleRow}>
          {/* Overall */}
          <TouchableOpacity
            style={[
              styles.togglePill,
              !showHistory && styles.toggleActive,  // filled when overall is showing
            ]}
            onPress={() => setShowHistory(false)}
          >
            <Text style={[
              styles.toggleTxt,
              !showHistory && styles.toggleTxtActive,
            ]}>
              Overall
            </Text>
          </TouchableOpacity>

          {/* History */}
          <TouchableOpacity
            style={[
              styles.togglePill,
              showHistory && styles.toggleActive,   // filled when history is showing
            ]}
            onPress={() => setShowHistory(true)}
          >
            <Text style={[
              styles.toggleTxt,
              showHistory && styles.toggleTxtActive,
            ]}>
              History
            </Text>
          </TouchableOpacity>
        </View>

        {/* date-range (only visible in history mode) */}
        {showHistory && (
          <View style={styles.dateRow}>
            {/* start */}
            <TouchableOpacity
              style={styles.dateBtn}
              onPress={() => setPicker("start")}
            >
              <Ionicons name="calendar-outline" size={16} color="#ffd700" />
              <Text style={styles.dateTxt}>{startDate ?? "Start date"}</Text>
            </TouchableOpacity>

            {/* end */}
            <TouchableOpacity
              style={styles.dateBtn}
              onPress={() => setPicker("end")}
            >
              <Ionicons name="calendar-outline" size={16} color="#ffd700" />
              <Text style={styles.dateTxt}>{endDate ?? "End date"}</Text>
            </TouchableOpacity>
          </View>
        )}

        {/* search */}
        <View style={styles.searchBox}>
          <Ionicons name="search" size={18} color="#999" />
          <TextInput
            placeholder="Search players…"
            placeholderTextColor="#999"
            style={styles.searchInput}
            value={query}
            onChangeText={setQuery}
          />
        </View>

        {/* pickers (native) */}
        {picker && (
          <DateTimePicker
            value={
              picker === "start"
                ? (startDate ? parseLocalDate(startDate) : (minDate ?? new Date()))
                : (endDate   ? parseLocalDate(endDate)   : (maxDate ?? new Date()))
            }
            mode="date"
            display={Platform.OS === "ios" ? "inline" : "default"}
            minimumDate={minDate ?? new Date()}
            maximumDate={maxDate ?? new Date()}
            onChange={(_, d) => {
              if (!d) { setPicker(null); return; }
              const iso = toISODate(d);          // ← use UTC-midnight date
              if (picker === "start") setStartDate(iso);
              else                     setEndDate(iso);
              setPicker(null);
            }}
          />
        )}

        {/* errors / loader */}
        {loading && <ActivityIndicator color="#FFD700" style={{ marginTop: 30 }} />}
        {err && <Text style={styles.error}>{err}</Text>}

        {/* list */}
        {!loading && !err && (
          showHistory ? (
            <SectionList
              sections={sectionData}
              keyExtractor={item => item.name + item.rank}
              renderItem={renderRow}
              renderSectionHeader={({ section: { title } }) => (
                <Text style={styles.sectionHeader}>{title}</Text>
              )}
              contentContainerStyle={{ paddingBottom: 60 }}
              stickySectionHeadersEnabled={false}
            />
          ) : (
            <SectionList
              sections={[{ title: "", data: listData }]}
              keyExtractor={item => item.name}
              renderItem={renderRow}
              contentContainerStyle={{ paddingBottom: 60 }}
              stickySectionHeadersEnabled={false}
            />
          )
        )}
      </View>
    </ImageBackground>
  );
};

export default LeaderboardDetails;

/* ───────────────────────── styles ───────────────────────── */
const styles = StyleSheet.create({
  bg: { flex: 1 },
  container: { flex: 1, paddingTop: 50, paddingHorizontal: 20 },
  header: { flexDirection: "row", alignItems: "center", marginBottom: 20 },
  h1: { flex: 1, textAlign: "center", color: "#fff", fontSize: 28, fontWeight: "700" },
  iconBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: "rgba(255,255,255,0.2)", alignItems: "center", justifyContent: "center" },

  /* ── styles ── */
  toggleRow:  { flexDirection: 'row', alignSelf: 'center', marginBottom: 15 },
  togglePill: { paddingHorizontal: 28, paddingVertical: 10, borderRadius: 18,
              marginHorizontal: 4, borderWidth: 1,
              borderColor: 'rgba(255,255,255,0.5)', backgroundColor: 'transparent' },
  toggleActive: { backgroundColor: 'rgba(255,255,255,0.25)' },
  toggleTxt:  { color: '#fff', fontWeight: '600' },
  toggleTxtActive: { color: '#FFD700' },

  dateRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 10 },
  dateBtn: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(50,50,60,0.30)", paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, flex: 1, marginHorizontal: 4 },
  dateTxt: { marginLeft: 6, color: "#fff" },

  searchBox: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(50,50,60,0.30)", borderRadius: 15, paddingHorizontal: 14, marginBottom: 18 },
  searchInput: { flex: 1, height: 44, color: "#fff", marginLeft: 6 },

  error: { color: "#F88", textAlign: "center", marginTop: 20 },

  sectionHeader: { marginTop: 24, marginBottom: 8, fontSize: 18, fontWeight: "700", color: "#FFD700" },

  row: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(50,50,60,0.25)", borderRadius: 14, padding: 14, marginBottom: 10 },
  meRow: { backgroundColor: "rgba(255,215,0,0.20)" },
  rank: { width: 36, color: "#FFD700", fontWeight: "600" },
  name: { flex: 1, color: "#fff", fontSize: 16, fontWeight: "600" },
  meName: { color: "#FFD700" },
  points: { width: 80, textAlign: "right", color: "#FFD700", fontWeight: "700" },
});
