// This file was auto-generated by openapi-typescript

import React, { useEffect, useState } from "react";
import { useFocusEffect } from "@react-navigation/native";
import { useCallback } from "react";
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  FlatList,
  Alert,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import axios from "axios";
import { NavigationProp } from "@react-navigation/native";
import { useUser } from '../../context/UserContext';
import { BASE_URL, endpoints } from "../../api";
import { useRoute } from '@react-navigation/native';
import { getAccessToken } from "../../auth";

type Props = { navigation: NavigationProp<any> };

type Obligation = {
  id: number;
  challenge: number;
  payer: number | { id: number; username: string };  // can be id or object
  payer_name?: string;     // added
  payee: number | { id: number; username: string };  // can be id or object
  payee_name?: string;     // added
  currency: string;
  reward_type?: 'money' | 'points' | 'custom';
  reward_note?: string;
  amount: string;
  status: "unpaid" | "pending" | "paid";
  remaining: string;
  payments: Payment[];
};

type Payment = {
  id: number;
  method: "cash" | "external" | "custom";
  provider: string | null;
  amount: string;
  note?: string;
  status: "pending" | "confirmed" | "rejected";
};

const RewardSettleScreen: React.FC<Props> = ({ navigation }) => {
  const { user } = useUser();
  const [data, setData] = useState<Obligation[]>([]);
  const [loading, setLoading] = useState(false);
  const [toPay, setToPay] = useState<Obligation[]>([]);
  const [toReceive, setToReceive] = useState<Obligation[]>([]);
    const route = useRoute<any>();
    const challengeId = route.params?.challengeId as number | undefined;

    useFocusEffect(useCallback(() => { refresh(); }, [user?.id, challengeId]));

    const refresh = async () => {
      if (!user) return;
      try {
        setLoading(true);
              const accessToken = await getAccessToken();
              if (!accessToken) {
                throw new Error("Not authenticated");
              }
        const res = await axios.get(endpoints.myObligations(), {
                headers: {
                  Authorization: `Bearer ${accessToken}`
                }
              });
        let tp = Array.isArray(res.data?.to_pay) ? res.data.to_pay : [];
        let tr = Array.isArray(res.data?.to_receive) ? res.data.to_receive : [];

        if (challengeId) {
          tp = tp.filter((o: any) => o.challenge === challengeId);
          tr = tr.filter((o: any) => o.challenge === challengeId);
        }

        setToPay(tp);
        setToReceive(tr);
      } catch (e) {
        console.error("load obligations", e);
        Alert.alert("Error", "Could not load obligations");
      } finally {
        setLoading(false);
      }
    };

  /** ---------- helper actions ---------- */
  const nameOf = (name?: string, id?: number) =>
    (name && name.trim().length ? name : `User #${id}`);

  const post = async (url: string, onOk: () => void) => {
    try {
            const accessToken = await getAccessToken();
            if (!accessToken) {
              throw new Error("Not authenticated");
            }
      await axios.post(url, {}, {
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      });
      onOk();
    } catch (e) {
      console.error(e);
      Alert.alert("Error", "Request failed");
    }
  };

    const handlePayExt = async (ob: Obligation) => {
      try {
      const accessToken = await getAccessToken();
      if (!accessToken) {
        throw new Error("Not authenticated");
      }

        const payload = {
          provider: "venmo",
          amount: ob.remaining?.toString(),
          note: `Reward for challenge ${ob.challenge ?? ""}`,
        };

        const res = await fetch(endpoints.payExternal(ob.id), {
          method: "POST",
        headers: {
          'Content-Type': 'application/json',
          "Authorization": `Bearer ${accessToken}`,
        },
          body: JSON.stringify(payload),
        });

        if (!res.ok) {
          const err = await res.json().catch(() => ({}));
          throw new Error(err.detail || err.message || "Failed to record external payment");
        }

        await refresh();
      } catch (err: any) {
        Alert.alert("Error", err.message);
      }
    };

    const handleCustomDone = async (ob: Obligation) => {
    Alert.alert(
      'Confirm',
      'Have you already fulfilled the custom reward for the winner? Make sure you have completed it before confirming.',
      [
        { text: 'Cancel', style: 'cancel' },
        { text: 'Yes, I did', onPress: async () => {
          try {
      const accessToken = await getAccessToken();
      if (!accessToken) {
        throw new Error("Not authenticated");
      }
            await fetch(endpoints.payCustom(ob.id), {
              method:'POST',
        headers: {
          'Content-Type': 'application/json',
          "Authorization": `Bearer ${accessToken}`,
        },
              body: JSON.stringify({ note: ob.reward_note || 'Custom reward fulfilled'})
            });
            await refresh();
          } catch(e:any){ Alert.alert('Error', e.message) }
        } },
      ]
    );
  };

  const handlePayCash = async (
      ob: Obligation,
      opts?: { amount?: number | string; note?: string }
    ) => {
      try {
      const accessToken = await getAccessToken();
      if (!accessToken) {
        throw new Error("Not authenticated");
      }

        //POST cash payment
        const payload = {
          amount: (opts?.amount ?? ob.remaining).toString(),
          note: opts?.note ?? "Cash payment",
        };

        const res = await fetch(endpoints.payCash(ob.id), {
          method: "POST",
        headers: {
          'Content-Type': 'application/json',
          "Authorization": `Bearer ${accessToken}`,
        },
          body: JSON.stringify(payload),
        });

        if (!res.ok) {
          const err = await res.json().catch(() => ({}));
          throw new Error(err.message || "Failed to record cash payment");
        }

        await refresh();
      } catch (err: any) {
        Alert.alert("Error", err.message);
      }
    };

    const handleConfirm = async (p: Payment) => {
      try {
      const accessToken = await getAccessToken();
      if (!accessToken) {
        throw new Error("Not authenticated");
      }


        const res = await fetch(endpoints.confirmPayment(p.id), {
          method: "POST",
        headers: {
          'Content-Type': 'application/json',
          "Authorization": `Bearer ${accessToken}`,
        },
        });

        if (!res.ok) {
          const err = await res.json();
          throw new Error(err.message || "Failed to confirm payment");
        }

        await refresh();
      } catch (err: any) {
        Alert.alert("Error", err.message);
      }
    };

    const handleReject = async (p: Payment) => {
      try {
      const accessToken = await getAccessToken();
      if (!accessToken) {
        throw new Error("Not authenticated");
      }


        const res = await fetch(endpoints.rejectPayment(p.id), {
          method: "POST",
        headers: {
          'Content-Type': 'application/json',
          "Authorization": `Bearer ${accessToken}`,
        },
        });

        if (!res.ok) {
          const err = await res.json();
          throw new Error(err.message || "Failed to reject payment");
        }

        await refresh();
      } catch (err: any) {
        Alert.alert("Error", err.message);
      }
    };

  /** ---------- render ---------- */
  const renderOb = ({ item }: { item: Obligation }) => {
    const isCustom = item.reward_type === 'custom' || item.currency === 'CST' || parseFloat(item.amount) === 0;
    const isPoints = item.reward_type === 'points' || item.currency === 'PTS';

    const payerObj = typeof item.payer === 'object' ? item.payer : null;
    const payeeObj = typeof item.payee === 'object' ? item.payee : null;

    const payerId   = typeof item.payer === 'number' ? item.payer : item.payer.id;
    const payeeId   = typeof item.payee === 'number' ? item.payee : item.payee.id;
    const payerName = (item as any).payer_name ?? (payerObj?.username ?? `User #${payerId}`);
    const payeeName = (item as any).payee_name ?? (payeeObj?.username ?? `User #${payeeId}`);

    const iamPayer  = payerId === user?.id;
    const iamWinner = payeeId === user?.id;

    return (
      <View style={styles.card}>
        <Text style={styles.title}>
          {iamPayer ? `You → ${payeeName}` : `${payerName} → You`}
        </Text>
        {isCustom && item.reward_note ? (
          <Text style={styles.customTitle}>{item.reward_note}</Text>
        ) : null}
        <Text style={styles.subtitle}>
          {isCustom ? ('Custom reward') : isPoints ? `${item.remaining} pts / ${item.amount} pts` : `$${item.remaining} / $${item.amount}`} ({item.status})
        </Text>

        {/* payer actions */}

        {iamPayer && item.status === "unpaid" && (
          isCustom ? (
            <TouchableOpacity style={[styles.btn,{marginTop:6}]} onPress={() => handleCustomDone(item)}>
              <Ionicons name="checkmark" size={18} color="#000" />
              <Text style={styles.btnText}>Confirm custom reward done</Text>
            </TouchableOpacity>
          ) : (
            <View style={styles.actionRow}>
              <TouchableOpacity style={styles.btn} onPress={() => handlePayExt(item)}>
                <Ionicons name="card" size={18} color="#fff" />
                <Text style={styles.btnText}>Pay Venmo/PayPal</Text>
              </TouchableOpacity>
              <TouchableOpacity style={styles.btn} onPress={() => handlePayCash(item)}>
                <Ionicons name="cash" size={18} color="#fff" />
                <Text style={styles.btnText}>Record Cash</Text>
              </TouchableOpacity>
            </View>
          )
        )}

        {/* winner actions */}
        {iamWinner &&
          item.payments
            .filter((p) => p.status === "pending")
            .map((p) => (
              <View key={p.id} style={styles.actionRow}>
                <Text style={styles.pendingTxt}>
                  {payerName} sent {isCustom ? (item.reward_note || 'custom reward') : isPoints ? `${p.amount} pts` : `$${p.amount} (${p.method})`}
                </Text>
                <TouchableOpacity style={styles.iconBtn} onPress={() => handleConfirm(p)}>
                  <Ionicons name="checkmark-circle" size={26} color="#4caf50" />
                </TouchableOpacity>
                <TouchableOpacity style={styles.iconBtn} onPress={() => handleReject(p)}>
                  <Ionicons name="close-circle" size={26} color="#f44336" />
                </TouchableOpacity>
              </View>
        ))}
      </View>
    );
  };

  return (
    <View style={styles.container}>
      <TouchableOpacity
        style={styles.back}
        onPress={() => navigation.goBack()}
      >
        <Ionicons name="arrow-back" size={24} color="#fff" />
      </TouchableOpacity>

    <Text style={styles.header}>Rewards & Settlements</Text>

    <Text style={{ color:"#fff", fontWeight:"700", marginLeft:20, marginBottom:6 }}>You owe</Text>
    <FlatList
      data={toPay}
      keyExtractor={(o) => o.id.toString()}
      renderItem={renderOb}
      ListEmptyComponent={<Text style={{ color:"#aaa", marginLeft:20 }}>Nothing to pay 🎉</Text>}
    />

    <Text style={{ color:"#fff", fontWeight:"700", marginLeft:20, marginTop:20, marginBottom:6 }}>You’ll receive</Text>
    <FlatList
      data={toReceive}
      keyExtractor={(o) => o.id.toString()}
      renderItem={renderOb}
      ListEmptyComponent={<Text style={{ color:"#aaa", marginLeft:20 }}>No one owes you yet</Text>}
    />
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#121016", paddingTop: 50 },
  back: { position: "absolute", top: 54, left: 20, zIndex: 10 },
  header: {
    fontSize: 26,
    fontWeight: "700",
    color: "#ffd700",
    textAlign: "center",
    marginBottom: 20,
  },
  card: {
    backgroundColor: "rgba(255,255,255,0.08)",
    marginHorizontal: 20,
    marginBottom: 16,
    padding: 16,
    borderRadius: 14,
  },
  title: { color: "#fff", fontSize: 16, fontWeight: "600" },
  customTitle: { fontSize:18, color:'#ffd700', fontWeight:'600', marginBottom:4, marginTop:4 },
  subtitle: { color: "#aaa", marginBottom: 8 },
  actionRow: { flexDirection: "row", alignItems: "center", marginTop: 6 },
  btn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffd700",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 18,
    marginRight: 8,
  },
  btnText: { marginLeft: 6, fontWeight: "600", color: "#000" },
  pendingTxt: { flex: 1, color: "#fff" },
  iconBtn: { marginLeft: 8 },
});

export default RewardSettleScreen;