// This file was auto-generated by openapi-typescript

import React, { useEffect, useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  FlatList,
  Alert,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import axios from "axios";
import { NavigationProp } from "@react-navigation/native";
import { useUser } from '../../context/UserContext';
import { endpoints } from "../../api";

type Props = { navigation: NavigationProp<any> };

type Obligation = {
  id: number;
  payer: { id: number; username: string };
  payee: { id: number; username: string };
  amount: string; // backend sends decimal → keep string
  status: "unpaid" | "pending" | "paid";
  remaining: string;
  payments: Payment[];
};

type Payment = {
  id: number;
  method: "cash" | "external";
  provider: "venmo" | "paypal" | "other";
  amount: string;
  status: "pending" | "confirmed" | "rejected";
};

const RewardSettleScreen: React.FC<Props> = ({ navigation }) => {
  const { user } = useUser();
  const [data, setData] = useState<Obligation[]>([]);
  const [loading, setLoading] = useState(false);

  const refresh = async () => {
    if (!user) return;
    try {
      setLoading(true);
      const res = await axios.get(endpoints.myObligations(), {
        withCredentials: true,
      });
      setData(res.data);
    } catch (e) {
      console.error("load obligations", e);
      Alert.alert("Error", "Could not load obligations");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    refresh();
  }, []);

  /** ---------- helper actions ---------- */
  const post = async (url: string, onOk: () => void) => {
    try {
      await axios.post(url, {}, { withCredentials: true });
      onOk();
    } catch (e) {
      console.error(e);
      Alert.alert("Error", "Request failed");
    }
  };

    const handlePayExt = async (ob: Obligation) => {
      try {
        // 1. Fetch csrf token
        const csrfRes = await fetch(`${BASE_URL}/api/csrf-token/`, {
          credentials: "include",
        });
        if (!csrfRes.ok) throw new Error("Failed to fetch CSRF token");
        const { csrfToken } = await csrfRes.json();

        // 2. Make the POST with csrf token
        const res = await fetch(endpoints.payExternal(ob.id), {
          method: "POST",
          credentials: "include",
          headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": csrfToken,
          },
        });

        if (!res.ok) {
          const err = await res.json();
          throw new Error(err.message || "Failed to record external payment");
        }

        await refresh();
      } catch (err: any) {
        Alert.alert("Error", err.message);
      }
    };

    const handlePayCash = async (
      ob: Obligation,
      opts?: { amount?: number | string; note?: string }
    ) => {
      try {
        // 1) fetch CSRF
        const csrfRes = await fetch(`${BASE_URL}/api/csrf-token/`, {
          credentials: "include",
        });
        if (!csrfRes.ok) throw new Error("Failed to fetch CSRF token");
        const { csrfToken } = await csrfRes.json();

        // 2) POST cash payment
        const payload = {
          amount: (opts?.amount ?? ob.remaining).toString(),
          note: opts?.note ?? "Cash payment",
        };

        const res = await fetch(endpoints.payCash(ob.id), {
          method: "POST",
          credentials: "include",
          headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": csrfToken,
          },
          body: JSON.stringify(payload),
        });

        if (!res.ok) {
          const err = await res.json().catch(() => ({}));
          throw new Error(err.message || "Failed to record cash payment");
        }

        await refresh();
      } catch (err: any) {
        Alert.alert("Error", err.message);
      }
    };

    const handleConfirm = async (p: Payment) => {
      try {
        const csrfRes = await fetch(`${BASE_URL}/api/csrf-token/`, {
          credentials: "include",
        });
        if (!csrfRes.ok) throw new Error("Failed to fetch CSRF token");
        const { csrfToken } = await csrfRes.json();

        const res = await fetch(endpoints.confirmPayment(p.id), {
          method: "POST",
          credentials: "include",
          headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": csrfToken,
          },
        });

        if (!res.ok) {
          const err = await res.json();
          throw new Error(err.message || "Failed to confirm payment");
        }

        await refresh();
      } catch (err: any) {
        Alert.alert("Error", err.message);
      }
    };

    const handleReject = async (p: Payment) => {
      try {
        const csrfRes = await fetch(`${BASE_URL}/api/csrf-token/`, {
          credentials: "include",
        });
        if (!csrfRes.ok) throw new Error("Failed to fetch CSRF token");
        const { csrfToken } = await csrfRes.json();

        const res = await fetch(endpoints.rejectPayment(p.id), {
          method: "POST",
          credentials: "include",
          headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": csrfToken,
          },
        });

        if (!res.ok) {
          const err = await res.json();
          throw new Error(err.message || "Failed to reject payment");
        }

        await refresh();
      } catch (err: any) {
        Alert.alert("Error", err.message);
      }
    };

  /** ---------- render ---------- */
  const renderOb = ({ item }: { item: Obligation }) => {
    const iamPayer = item.payer.id === user?.id;
    const iamWinner = item.payee.id === user?.id;

    return (
      <View style={styles.card}>
        <Text style={styles.title}>
          {iamPayer ? "You → " + item.payee.username : item.payer.username + " → You"}
        </Text>
        <Text style={styles.subtitle}>
          ${item.remaining} / ${item.amount} &nbsp;({item.status})
        </Text>

        {/* payer actions */}
        {iamPayer && item.status === "unpaid" && (
          <View style={styles.actionRow}>
            <TouchableOpacity style={styles.btn} onPress={() => handlePayExt(item)}>
              <Ionicons name="card" size={18} color="#fff" />
              <Text style={styles.btnText}>Pay Venmo/PayPal</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.btn} onPress={() => handlePayCash(item)}>
              <Ionicons name="cash" size={18} color="#fff" />
              <Text style={styles.btnText}>Record Cash</Text>
            </TouchableOpacity>
          </View>
        )}

        {/* winner actions */}
        {iamWinner &&
          item.payments
            .filter((p) => p.status === "pending")
            .map((p) => (
              <View key={p.id} style={styles.actionRow}>
                <Text style={styles.pendingTxt}>
                  {p.payer?.username ?? "Friend"} sent ${p.amount} ({p.method})
                </Text>
                <TouchableOpacity
                  style={styles.iconBtn}
                  onPress={() => handleConfirm(p)}
                >
                  <Ionicons name="checkmark-circle" size={26} color="#4caf50" />
                </TouchableOpacity>
                <TouchableOpacity
                  style={styles.iconBtn}
                  onPress={() => handleReject(p)}
                >
                  <Ionicons name="close-circle" size={26} color="#f44336" />
                </TouchableOpacity>
              </View>
            ))}
      </View>
    );
  };

  return (
    <View style={styles.container}>
      <TouchableOpacity
        style={styles.back}
        onPress={() => navigation.goBack()}
      >
        <Ionicons name="arrow-back" size={24} color="#fff" />
      </TouchableOpacity>

     <TouchableOpacity onPress={() => handlePayCash(ob)}>
       <Text>Record Cash</Text>
     </TouchableOpacity>

      <Text style={styles.header}>Rewards & Settlements</Text>

      <FlatList
        data={data}
        keyExtractor={(o) => o.id.toString()}
        renderItem={renderOb}
        refreshing={loading}
        onRefresh={refresh}
        contentContainerStyle={{ paddingBottom: 40 }}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#121016", paddingTop: 50 },
  back: { position: "absolute", top: 54, left: 20, zIndex: 10 },
  header: {
    fontSize: 26,
    fontWeight: "700",
    color: "#ffd700",
    textAlign: "center",
    marginBottom: 20,
  },
  card: {
    backgroundColor: "rgba(255,255,255,0.08)",
    marginHorizontal: 20,
    marginBottom: 16,
    padding: 16,
    borderRadius: 14,
  },
  title: { color: "#fff", fontSize: 16, fontWeight: "600" },
  subtitle: { color: "#aaa", marginBottom: 8 },
  actionRow: { flexDirection: "row", alignItems: "center", marginTop: 6 },
  btn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffd700",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 18,
    marginRight: 8,
  },
  btnText: { marginLeft: 6, fontWeight: "600", color: "#000" },
  pendingTxt: { flex: 1, color: "#fff" },
  iconBtn: { marginLeft: 8 },
});

export default RewardSettleScreen;