from django.urls import path

from .views import (AcceptPersonalChallenge, ConversationView, DeclinePersonalChallenge, 
                    ExternalHandleViewSet, FinalizeChallengeView, FinalizePublicChallengeView, 
                    GetMatchingChallengesView, GetPendingPublicChallengesView, GetPersonalChallengeInvites, 
                    GetPublicChallengesView, GetUserAvailabilityView, GroupConversationView, 
                    JoinPublicChallengeView, LoginView, ObligationViewSet, PaymentViewSet, RegisterView, 
                    GroupListView, HelloWorldView, SendMessageGroupView, SendMessageView, SetChallAvailabilityView, 
                    SetUserAvailabilityView, ShareChallengeView, SingOrMultGameListView, SomeCatsListView, 
                    UserGroupConversationsView, UserProfileView, GetChallengeScheduleView, AddGameToScheduleView,
                    UserMessagesView, GroupDetailsView, CatListView, GameListView,
                    ChallengeListView, GetChallengeInitiatorView,
                    ChallengeDetailView, ChallengeGameScheduleView, CreateManualGroupChallengeView,
                    CreatePendingCollaborativeGroupChallengeView, FriendListView,
                    AddGroupMemberView, SendFriendRequestView, FriendRequestListView,
                    RespondToFriendRequestView, FinalizeCollaborativeGroupChallengeScheduleView,
                    SentFriendRequestListView, AllUsersView, CancelFriendRequestView,
                    CreateGroupView, CreatePersonalChallengeView, GetChallengeInvitesView,
                    GetAvailabilitiesView, DeclineChallengeInviteView,
                    ChallengeLeaderboardView, SubmitGameScoresView, ChallengeDailyHistoryView,
                    SkillLevelsView, CreatePublicChallengeView, RewardSettingView, 
                    CreateSudokuGameView, ValidateSudokuMoveView, CreatePatternGameView, 
                    ValidatePatternMoveView, CreateWordleGameView, ValidateWordleMoveView, 
                    SavePushTokenView, UserNotificationsView, DeleteNotificationView)

from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework.routers import DefaultRouter


from .views import (
    AcceptPersonalChallenge,
    AddGameToScheduleView,
    AddGroupMemberView,
    AllUsersView,
    CancelFriendRequestView,
    CatListView,
    ChallengeDailyHistoryView,
    ChallengeDetailView,
    ChallengeGameScheduleView,
    ChallengeLeaderboardView,
    ChallengeListView,
    ConversationView,
    CreateGroupView,
    CreateManualGroupChallengeView,
    CreatePatternGameView,
    CreatePendingCollaborativeGroupChallengeView,
    CreatePersonalChallengeView,
    CreatePublicChallengeView,
    CreateSudokuGameView,
    CreateWordleGameView,
    DeclineChallengeInviteView,
    DeclinePersonalChallenge,
    ExternalHandleViewSet,
    FinalizeChallengeView,
    FinalizeCollaborativeGroupChallengeScheduleView,
    FinalizePublicChallengeView,
    FriendListView,
    FriendRequestListView,
    GameListView,
    GetAvailabilitiesView,
    GetChallengeInitiatorView,
    GetChallengeInvitesView,
    GetChallengeScheduleView,
    GetChallengeUserScheduleView,
    GetMatchingChallengesView,
    GetPendingPublicChallengesView,
    GetPersonalChallengeInvites,
    GetPublicChallengesView,
    GetUserAvailabilityView,
    GroupConversationView,
    GroupDetailsView,
    GroupListView,
    HelloWorldView,
    JoinPublicChallengeView,
    LoginView,
    ObligationViewSet,
    PaymentViewSet,
    RegisterView,
    RespondToFriendRequestView,
    RewardSettingView,
    SendFriendRequestView,
    SendMessageGroupView,
    SendMessageView,
    SentFriendRequestListView,
    SetChallAvailabilityView,
    SetUserAvailabilityView,
    ShareChallengeView,
    SingOrMultGameListView,
    SkillLevelsView,
    SomeCatsListView,
    SubmitGameScoresView,
    UserGroupConversationsView,
    UserMessagesView,
    UserProfileView,
    ValidatePatternMoveView,
    ValidateSudokuMoveView,
    ValidateWordleMoveView,
    GetHasSetAlarmsView,
    SetUserHasSetAlarmsView,
    GetPerformancesView,
    SaveFCMTokenView,
    SendGroupInviteView,
    RespondGroupInviteView
)


router = DefaultRouter()
router.register(r'external-handles', ExternalHandleViewSet, basename='external-handle')
router.register(r'obligations', ObligationViewSet, basename='obligation')
router.register(r'payments', PaymentViewSet, basename='payment')

urlpatterns = [
    path('', include(router.urls)),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('get-user-info/', GetUserInfoView.as_view(), name='get-user-info'),
    path('challenges/<int:challenge_id>/finalize/', FinalizeChallengeView.as_view(), name='finalize-challenge'),
    path('challenges/<int:chall_id>/reward/', RewardSettingView.as_view(), name='challenge-reward'),
    path('challenges/<int:user_id>/<str:which_chall>/', ChallengeListView.as_view(), name='challenge-list'),
    path('get-pending-public-challenges/<int:user_id>/', GetPendingPublicChallengesView.as_view(), name='get-pending-public-challenges'),
    path('get-public-challenges/<int:user_id>/', GetPublicChallengesView.as_view(), name='get-public-challenges'),
    path(
    'get-matching-challenges/<int:user_id>/<str:category_ids>/<str:sing_or_mult>/',
    GetMatchingChallengesView.as_view(),
    name='get-matching-challenges'
    ),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('user-groups/<int:user_id>/', GroupListView.as_view(), name='group-list'),
    path('user-friends/<int:user_id>/', FriendListView.as_view(), name='friend-list'),
    path('cats/', CatListView.as_view(), name='cat-list'),
    path('some-cats/', SomeCatsListView.as_view(), name='some-cats'),
    path('games/<int:cat_id>/<str:sing_or_mult>/', GameListView.as_view(), name='game-list'),
    path('games/<str:sing_or_mult>/', SingOrMultGameListView.as_view(), name='sing-or-mult-game-list'),
    path('hello/', HelloWorldView.as_view(), name='hello'),
    path('profile/<int:user_id>/', UserProfileView.as_view(), name='user-profile'),
    path('get-initiator/<int:chall_id>/', GetChallengeInitiatorView.as_view(), name='get-initiator'),
    path('messages/<int:user_id>/', UserMessagesView.as_view()),
    path('groups/<int:group_id>/', GroupDetailsView.as_view(), name='group-details'),
    path('user/<int:user_id>/group-conversations/', UserGroupConversationsView.as_view(), name='user-group-conversations'),
    path('group-member-add/<int:group_id>/', AddGroupMemberView.as_view(), name='group-mem-add'),
    path('join-public-challenge/<int:user_id>/', JoinPublicChallengeView.as_view(), name='join-public-challenge'),
    path('finalize-public-challenge/', FinalizePublicChallengeView.as_view(), name='finalize-public-challenge'),
    path('challenge-detail/<int:chall_id>/', ChallengeDetailView.as_view(), name='challenge-detail'),
    path('challenge-schedule/<int:chall_id>/', ChallengeGameScheduleView.as_view(), name='challenge-schedule'),
    path('get-challenge-schedule/<int:chall_id>/', GetChallengeScheduleView.as_view(), name='get-challenge-schedule'),
    path('get-challenge-user-schedule/<int:chall_id>/<int:user_id>/', GetChallengeUserScheduleView.as_view(), name='get-challenge-user-schedule'),
    path('get-has-set-alarms/<int:chall_id>/<int:user_id>/', GetHasSetAlarmsView.as_view(), name='get-has-set-alarms'),
    path('set-user-has-set-alarms/<int:chall_id>/<int:user_id>/', SetUserHasSetAlarmsView.as_view(), name='set-user-has-set-alarms'),
    path('create-manual-group-challenge/', CreateManualGroupChallengeView.as_view(), name='create-manual-group-challenge'),
    path('create-public-challenge/', CreatePublicChallengeView.as_view(), name='create-public-challenge'),
    path('create-pending-collaborative-group-challenge/', CreatePendingCollaborativeGroupChallengeView.as_view(), name='create-pending-collaborative-group-challenge'),
    path('finalize-collaborative-group-challenge-schedule/<int:chall_id>/', FinalizeCollaborativeGroupChallengeScheduleView.as_view(), name='finalize-collaborative-group-challenge-schedule'),
    path('friend-requests/<int:user_id>/', FriendRequestListView.as_view(), name='friend-requests'),
    path('friend-requests-sent/<int:user_id>/', SentFriendRequestListView.as_view(), name='sent-friend-requests'),
    path('friend-request/respond/<int:request_id>/', RespondToFriendRequestView.as_view(), name='respond-friend-request'),
    path('friend-request/send/', SendFriendRequestView.as_view(), name='send-friend-request'),
    path('get-challenge-invites/<int:user_id>/<int:group_id>/', GetChallengeInvitesView.as_view(), name='get-challenge-invites'),
    # path('challenge-invites/<int:user_id>/<int:group_id>/', ChallengeInvitesListView.as_view(), name='challenge-invites'),
    
    # path('get-pending-challenges/<int:group_id>/', GetPendingChallengesView.as_view(), name='get-pending-challenges'),
    path('get-availabilities/<int:chall_id>/', GetAvailabilitiesView.as_view(), name='get-availabilities'),
    path('set-user-availability/<int:user_id>/', SetUserAvailabilityView.as_view(), name='set-user-availability'),
    path('get-user-availability/<int:user_id>/', GetUserAvailabilityView.as_view(), name='get-user-availability'),
    path('set-chall-availability/<int:user_id>/<int:chall_id>/', SetChallAvailabilityView.as_view(), name='set-chall-availability'),
    path('decline-challenge-invite/<int:user_id>/<int:chall_id>/', DeclineChallengeInviteView.as_view(), name='decline-challenge-invite'),
    path('messages/send/<int:user_id>/', SendMessageView.as_view(), name='send-message'),
    path('messages/send/group/<int:group_id>/', SendMessageGroupView.as_view()),
    path("push-tokens/", SavePushTokenView.as_view(), name="save_push_token"),
    path('save-fcm-token/', SaveFCMTokenView.as_view()),
    path('conversation/<int:user_id>/<int:recipient_id>/', ConversationView.as_view(), name='conversation'),
    path('conversation/group/<int:group_id>/', GroupConversationView.as_view(), name='conversation-group'),
    path('profile/all/', AllUsersView.as_view(), name='all-users'),
    path('friend-request/delete/<int:request_id>/', CancelFriendRequestView.as_view(), name='cancel-friend-request'),
    path('create-group/', CreateGroupView.as_view(), name='create-group'),
    path('sudoku/create/', CreateSudokuGameView.as_view(), name='create-sudoku'),
    path('sudoku/validate/', ValidateSudokuMoveView.as_view(), name='validate-sudoku'),
    path('wordle/create/', CreateWordleGameView.as_view(), name='create-wordle'),
    path('wordle/validate/', ValidateWordleMoveView.as_view(), name='validate-wordle'),
    path("create-personal-challenge/", CreatePersonalChallengeView.as_view(), name="create_personal_challenge"),
    path('pattern/create/',   CreatePatternGameView.as_view(),   name='pattern-create'),
    path('pattern/validate/', ValidatePatternMoveView.as_view(), name='pattern-validate'),
    path('challenge-leaderboard/<int:chall_id>/', ChallengeLeaderboardView.as_view(), name='challenge-leaderboard'),
    path("challenge-leaderboard/<int:chall_id>/history/", ChallengeDailyHistoryView.as_view(), name="challenge-leaderboard-history"),
    path('get-performances/<int:chall_id>/', GetPerformancesView.as_view(), name='get-performances'),
    path('submit-game-scores/', SubmitGameScoresView.as_view(), name='submit-game-scores'),
    path('add-game-to-schedule/', AddGameToScheduleView.as_view(), name='add-game-to-schedule'),
    path('skill-levels/', SkillLevelsView.as_view(), name="skill-levels"),

    # sending challenge to friends
    path("share-challenge/<int:chall_id>/", ShareChallengeView.as_view()),
    path("share-challenge/", ShareChallengeView.as_view()),
    path('get-personal-challenge-invites/<int:user_id>/', GetPersonalChallengeInvites.as_view()),
    path('accept-personal-challenge/<int:user_id>/<int:chall_id>/', AcceptPersonalChallenge.as_view()),
    path('decline-personal-challenge/<int:user_id>/<int:chall_id>/', DeclinePersonalChallenge.as_view()),
    path('save-push-token/', SavePushTokenView.as_view(), name='save-push-token'),
    path('notifications/<int:user_id>/', UserNotificationsView.as_view(), name='user-notifications'),
    path("notifications/<int:notification_id>/delete/", DeleteNotificationView.as_view(), name="delete-notification"),

    path('groups/invite/', SendGroupInviteView.as_view()),
    path('groups/invite/respond/<int:invite_id>/', RespondGroupInviteView.as_view()),
]