from django.urls import path
from .views import (LoginView, RegisterView, GroupListView, HelloWorldView, UserProfileView, 
                    UserMessagesView, GroupDetailsView, CatListView, GameListView, ChallengeListView, 
                    ChallengeDetailView, ChallengeGameScheduleView, CreateGroupChallengeView, CreatePendingGroupChallengeView, FriendListView, 
                    AddGroupMemberView, SendFriendRequestView, FriendRequestListView, RespondToFriendRequestView,
                    SentFriendRequestListView, AllUsersView, CancelFriendRequestView, CreateGroupView, CreatePersonalChallengeView, GetChallengeInvitesView,
                    GetAvailabilitiesView, SetAvailabilityView, DeclineChallengeInviteView, ChallengeLeaderboardView, SubmitGameScoresView, ChallengeDailyHistoryView)

from .views import CreateSudokuGameView, ValidateSudokuMoveView, get_csrf_token

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('user-groups/<int:user_id>/', GroupListView.as_view(), name='group-list'),
    path('user-friends/<int:user_id>/', FriendListView.as_view(), name='friend-list'),
    path('cats/', CatListView.as_view(), name='cat-list'),
    path('games/<int:cat_id>/<str:sing_or_mult>/', GameListView.as_view(), name='game-list'),
    path('hello/', HelloWorldView.as_view(), name='hello'),
    path('profile/<int:user_id>/', UserProfileView.as_view(), name='user-profile'),
    path('messages/<int:user_id>/', UserMessagesView.as_view()),
    path('groups/<int:group_id>/', GroupDetailsView.as_view(), name='group-details'),
    path('group-member-add/<int:group_id>/', AddGroupMemberView.as_view(), name='group-mem-add'),
    path('challenges/<int:user_id>/<str:which_chall>/', ChallengeListView.as_view(), name='challenge-list'),
    path('challenge-detail/<int:chall_id>/', ChallengeDetailView.as_view(), name='challenge-detail'),
    path('challenge-schedule/<int:chall_id>/', ChallengeGameScheduleView.as_view(), name='challenge-schedule'),
    path('create-group-challenge/', CreateGroupChallengeView.as_view(), name='create-group-challenge'),
    path('create-pending-group-challenge/', CreatePendingGroupChallengeView.as_view(), name='create-group-challenge'),
    path('friend-requests/<int:user_id>/', FriendRequestListView.as_view(), name='friend-requests'),
    path('friend-requests-sent/<int:user_id>/', SentFriendRequestListView.as_view(), name='sent-friend-requests'),
    path('friend-request/respond/<int:request_id>/', RespondToFriendRequestView.as_view(), name='respond-friend-request'),
    path('friend-request/send/', SendFriendRequestView.as_view(), name='send-friend-request'),
    path('get-challenge-invites/<int:user_id>/<int:group_id>/', GetChallengeInvitesView.as_view(), name='get-challenge-invites'),
    # path('challenge-invites/<int:user_id>/<int:group_id>/', ChallengeInvitesListView.as_view(), name='challenge-invites'),
    
    # path('get-pending-challenges/<int:group_id>/', GetPendingChallengesView.as_view(), name='get-pending-challenges'),
    path('get-availabilities/<int:chall_id>/', GetAvailabilitiesView.as_view(), name='get-availabilities'),
    path('set-availability/<int:user_id>/<int:chall_id>/', SetAvailabilityView.as_view(), name='set-availability'),
    path('decline-challenge-invite/<int:user_id>/<int:chall_id>/', DeclineChallengeInviteView.as_view(), name='decline-challenge-invite'),

    path('profile/all/', AllUsersView.as_view(), name='all-users'),
    path('friend-request/delete/<int:request_id>/', CancelFriendRequestView.as_view(), name='cancel-friend-request'),
    path('create-group/', CreateGroupView.as_view(), name='create-group'),
    path('sudoku/create/', CreateSudokuGameView.as_view(), name='create-sudoku'),
    path('sudoku/validate/', ValidateSudokuMoveView.as_view(), name='validate-sudoku'),
    path('csrf-token/', get_csrf_token, name='get-csrf-token'),
    path("create-personal-challenge/", CreatePersonalChallengeView.as_view(), name="create_personal_challenge"),
    path('challenge-leaderboard/<int:chall_id>/', ChallengeLeaderboardView.as_view(), name='challenge-leaderboard'),
    path("challenge-leaderboard/<int:chall_id>/history/", ChallengeDailyHistoryView.as_view(), name="challenge-leaderboard-history"),
    path('submit-game-scores/', SubmitGameScoresView.as_view(), name='submit-game-scores'),
]
